<template>
  <section class="flex flex-col md:flex-row p-4 bg-gray">
      <!--Left side-->
      <div class="w-full md:w-1/2 flex flex-col justify-center items-center ">
          <div class="max-w-md mx-auto mt-10 space-y-8">
              
                <p class="text-5xl md:text-6xl font-bold font-robot text-pop-up-top">
              Blogger,
              </p>
              <p class="text-5xl md:text-6xl font-bold font-robot relative -top-4 text-pop-up-top">Web Developer</p>
              <p class="w-96 text-justify text-lg leading-8">I am a full-stack web developer based in Nairobi. I love building and working on diverse distributed teams.</p>
          <router-link :to="{name:'blogs.vue'}" class="block" id="portfolio-btn"><button class="w-full md:w-48 btns border-2 border-black py-2 hover:text-white font-bold hover:bg-primaryColor hover:scale-[1.1] ease-out duration-300">Portfolio</button></router-link>
          </div>
          <div id="social-icons" class="w-full md:w-96 flex justify-center space-x-10 mt-28 md:relative md:right-5 md:justify-start">
            <a href="https://linkedin.com/in/ian-mugenya" target="_blank"><i class="fa-brands fa-linkedin text-3xl md:text-2xl hover:text-primaryColor hover:scale-[1.1] ease-out duration-300"></i></a>
            <a href="https://twitter.com/McBooll" target="_blank"><i class="fa-brands fa-twitter text-3xl md:text-2xl hover:text-primaryColor hover:scale-[1.1] ease-out duration-300"></i></a>
            <a href="#" target="_blank"><i class="fa-brands fa-github text-3xl md:text-2xl hover:text-primaryColor hover:scale-[1.1] ease-out duration-300"></i></a>
            <a href="https://medium.com/@ianmugenya" target="_blank"><i class="fa-brands fa-medium text-3xl md:text-2xl hover:text-primaryColor hover:scale-[1.1] ease-out duration-300"></i></a>
            <a href="https://dev.to/ianmcbull" target="_blank"><i class="fa-brands fa-dev text-3xl md:text-2xl hover:text-primaryColor hover:scale-[1.1] ease-out duration-300"></i></a>
          </div>
      </div>
      <!--Right Side-->
      <div class="w-full md:w-1/2 mt-4 md:mt-0">
        <img src="@/assets/landing.png" alt="Landing page image" class="md:w-3/4"/>
      </div>
  </section>

  
</template>
<script lang="ts">
import { defineComponent } from "vue";
export default defineComponent({
  mounted(){
    // setInterval(()=>{
    //   this.addVibration(document.querySelector('#portfolio-btn'));
    // },7000)
  },
  methods:{
    addVibration(element: HTMLElement | null) {
  element.classList.add('vibrate-1');
  setTimeout(() => {
    element.classList.remove('vibrate-1');
  }, 2000);
  }
  }

});
</script>

<style>
.vibrate-1 {
	-webkit-animation: vibrate-1 0.3s linear infinite both;
	        animation: vibrate-1 0.3s linear infinite both;
}
/* ----------------------------------------------
 * Generated by Animista on 2022-9-1 10:17:6
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation vibrate-1
 * ----------------------------------------
 */
 
 @-webkit-keyframes vibrate-1 {
  0% {
    -webkit-transform: translate(0);
            transform: translate(0);
  }
  20% {
    -webkit-transform: translate(-2px, 2px);
            transform: translate(-2px, 2px);
  }
  40% {
    -webkit-transform: translate(-2px, -2px);
            transform: translate(-2px, -2px);
  }
  60% {
    -webkit-transform: translate(2px, 2px);
            transform: translate(2px, 2px);
  }
  80% {
    -webkit-transform: translate(2px, -2px);
            transform: translate(2px, -2px);
  }
  100% {
    -webkit-transform: translate(0);
            transform: translate(0);
  }
}
@keyframes vibrate-1 {
  0% {
    -webkit-transform: translate(0);
            transform: translate(0);
  }
  20% {
    -webkit-transform: translate(-2px, 2px);
            transform: translate(-2px, 2px);
  }
  40% {
    -webkit-transform: translate(-2px, -2px);
            transform: translate(-2px, -2px);
  }
  60% {
    -webkit-transform: translate(2px, 2px);
            transform: translate(2px, 2px);
  }
  80% {
    -webkit-transform: translate(2px, -2px);
            transform: translate(2px, -2px);
  }
  100% {
    -webkit-transform: translate(0);
            transform: translate(0);
  }
}

</style>